version: '2'

services:
  mqtt:
    image: eclipse-mosquitto:1.4.10
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/config/:/mosquitto/config

  node-red:
    image: machinedata/node-red
    volumes:
      - ./node-red/data:/data
    ports:
      - 80:1880
    external_links:
      - mqtt:mqtt
      - mongodb:mongodb
    command: [sh, -c, "cd /data 
      && npm i node-red-contrib-meo-esp node-red-dashboard 
      && npm i  node-red-contrib-mongodb2
      && node-red --settings /data/settings.js"]
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
